// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelSeparation():Promise<void>;

export function ExportStem(arg1:string):Promise<string>;

export function InitialTrack():Promise<main.Track>;

export function LoadTrack(arg1:string):Promise<main.Track>;

export function LogFrontend(arg1:string,arg2:string):Promise<void>;

export function OpenAudio():Promise<main.Track>;

export function SelfTest():Promise<boolean>;

export function SeparateStems():Promise<Array<main.Stem>>;
