// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelSeparation() {
  return window['go']['main']['App']['CancelSeparation']();
}

export function ExportStem(arg1) {
  return window['go']['main']['App']['ExportStem'](arg1);
}

export function InitialTrack() {
  return window['go']['main']['App']['InitialTrack']();
}

export function LoadTrack(arg1) {
  return window['go']['main']['App']['LoadTrack'](arg1);
}

export function LogFrontend(arg1, arg2) {
  return window['go']['main']['App']['LogFrontend'](arg1, arg2);
}

export function OpenAudio() {
  return window['go']['main']['App']['OpenAudio']();
}

export function SelfTest() {
  return window['go']['main']['App']['SelfTest']();
}

export function SeparateStems() {
  return window['go']['main']['App']['SeparateStems']();
}
